---
- name: Taking service status from all servers
  hosts: tag_Os_ubuntu
  gather_facts: yes
  become: yes

  tasks:

    - name: Gathering service facts
      service_facts:

    - name: print the service_facts
      debug:
        var: ansible_facts.services
