---
- name: Taking service status from all servers
  hosts: tag_Os_ubuntu
  gather_facts: yes
  become: yes

  tasks:

    - name: Gathering service facts
      service_facts:
      register: service_info

    - name: save service facts as json
      read_csv:
        path: /home/ubuntu/ervice_facts.csv
        content: "{{ service_info.ansible_facts.services | dict2items }}"
      
