---
- name: Gather Service Facts and Output as CSV
  hosts: tag_Os_ubuntu
  gather_facts: no
  tasks:
    - name: Gather service facts
      service_facts:
      register: service_facts_result
      
    - name: Format service facts into CSV
      set_fact:
        csv_data: "{{ csv_data | default([]) + [{'Hostname': inventory_hostname, 'Service': item.key, 'Status': item.value.state}] }}"
      loop: "{{ service_facts_result.ansible_facts.services | dict2items }}"
    
    - name: Generate CSV content using template
      template:
        src: /home/ubuntu/ansible/jinja2_template/sample.j2
        dest: /home/ubuntu/service_facts.csv
